"""
Area comparison: deterministic pros/cons, risk matrices, leader summaries,
and the frozen report payload.

Everything here is a pure function over metric bundles the app assembles
from its cached analyses — the SAME numbers the standalone area views show,
never a second analytical implementation. Claude never enters this module:
the payload built here is the ONLY thing the optional narrative layer may
see, and every fact in the PDF traces back to it.

Risk levels are categorical (Low / Moderate / High / Insufficient evidence)
— never probabilities. No master success score exists or is derivable here.
"""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

MAX_COMPARE_AREAS = 3

RISK_LEVELS = ("Low", "Moderate", "High", "Insufficient evidence")

#: The app and the PDF must read turnover identically — comparative
#: framing, never the raw band name.
TURNOVER_READ = {
    "Lower observed turnover": "Lower than comparison areas",
    "Typical": "Typical of comparison areas",
    "Higher observed turnover": "Higher than comparison areas",
    "Limited evidence": "Limited evidence",
}

LIMITATION = ("This analysis is a relative decision aid based on public and "
              "third-party data. It does not predict restaurant success or "
              "profitability.")

CLAUDE_DISCLOSURE = ("AI is used only to convert structured analytical "
                     "results into explanatory text. All scores and factual "
                     "metrics are generated by the deterministic analysis "
                     "pipeline.")


# ----------------------------------------------------------------- payload
class Fact(BaseModel):
    """One structured pro/con: a signal, never free prose."""
    signal_id: str
    label: str
    severity: str            # for cons: how much it matters; pros: strength
    metric: Optional[str] = None
    comparison: Optional[str] = None
    evidence_quality: Optional[str] = None


class RiskRow(BaseModel):
    category: str
    level: str               # one of RISK_LEVELS
    evidence: str            # confidence in the reading: High/Medium/Low/—
    why: str


class AreaReport(BaseModel):
    code: str
    name: str
    #: False when no cuisine was given: the index is then concept-free
    #: restaurant persistence, and every label must say so.
    fit_is_concept: bool = True
    fit_index: Optional[float] = None
    fit_band: Optional[str] = None
    evidence: Optional[str] = None
    competition_band: Optional[str] = None
    competition_detail: Optional[str] = None
    turnover: Optional[str] = None
    ped_band: Optional[str] = None
    ped_sites: int = 0
    restaurants_total: int = 0
    similar_count: Optional[int] = None
    closest_count: Optional[int] = None
    persistence_rate: Optional[float] = None
    cohort_n: int = 0
    income_context: Optional[float] = None
    population: Optional[float] = None
    pros: list[Fact] = []
    cons: list[Fact] = []
    risks: list[RiskRow] = []


class ComparisonReportPayload(BaseModel):
    concept_line: str
    plan_items: list[str] = []
    generated: str = ""
    areas: list[AreaReport] = []
    leaders: dict = {}
    recommendation: str = ""
    methodology: list[list[str]] = []
    limitations: list[str] = []
    claude_disclosure: str = CLAUDE_DISCLOSURE


# ---------------------------------------------------------------- pros/cons
def derive_area_pros(bundle: dict) -> list[Fact]:
    """Max 4 pros, strongest first, each traced to a deterministic signal."""
    out: list[Fact] = []
    concept = bundle.get("fit_is_concept", True)
    subject = "concept" if concept else "restaurant"
    if bundle.get("fit_band") == "Strong":
        out.append(Fact(signal_id="concept_fit", severity="high",
                        label=f"Strong relative {subject} fit"
                        if concept else
                        "Strong observed restaurant persistence",
                        metric=_fmt_fit(bundle),
                        evidence_quality=bundle.get("evidence")))
    elif bundle.get("fit_band") == "Promising":
        out.append(Fact(signal_id="concept_fit", severity="medium",
                        label=f"Above-baseline observed {subject} "
                              f"persistence",
                        metric=_fmt_fit(bundle),
                        evidence_quality=bundle.get("evidence")))
    if bundle.get("competition_band") == "Low":
        out.append(Fact(signal_id="competition", severity="high",
                        label="Lower direct comparable competition",
                        metric=bundle.get("competition_detail")))
    elif bundle.get("competition_band") == "Moderate":
        out.append(Fact(signal_id="competition", severity="low",
                        label="Moderate comparable competition",
                        metric=bundle.get("competition_detail")))
    if bundle.get("turnover") == "Lower observed turnover":
        out.append(Fact(signal_id="turnover", severity="high",
                        label="Lower observed restaurant turnover"))
    if bundle.get("ped_band") == "High":
        out.append(Fact(signal_id="pedestrian", severity="medium",
                        label="High measured pedestrian activity nearby",
                        metric=f"{bundle.get('ped_sites', 0)} DOT count "
                               f"site(s) in the area"))
    if bundle.get("evidence") == "High":
        out.append(Fact(signal_id="evidence", severity="medium",
                        label="Strong evidence quality",
                        comparison="cohort, inventory and ACS all present"))
    return out[:4]


def derive_area_cons(bundle: dict) -> list[Fact]:
    """
    Max 4 cons, most material first, each traced to a MEASURED signal.

    Absence of evidence is never a con: an area with no DOT count site or
    no cuisine to score is not thereby a worse location, and listing it
    among the negatives would make missing data read as risk. Unmeasured
    dimensions surface in the risk matrix as "Insufficient evidence" and in
    evidence quality — never here.
    """
    out: list[Fact] = []
    if bundle.get("competition_band") == "High":
        out.append(Fact(signal_id="competition", severity="high",
                        label="High comparable competitor density",
                        metric=bundle.get("competition_detail")))
    if bundle.get("fit_band") == "Mixed":
        out.append(Fact(
            signal_id="concept_fit", severity="high",
            label=("Concept fit at or below the citywide baseline"
                   if bundle.get("fit_is_concept", True) else
                   "Restaurant persistence at or below the citywide "
                   "baseline"),
            metric=_fmt_fit(bundle)))
    if bundle.get("turnover") == "Higher observed turnover":
        out.append(Fact(signal_id="turnover", severity="high",
                        label="Higher observed restaurant turnover"))
    if bundle.get("ped_band") == "Low":
        out.append(Fact(signal_id="pedestrian", severity="medium",
                        label="Low measured pedestrian activity nearby",
                        metric=f"{bundle.get('ped_sites', 0)} DOT count "
                               f"site(s) in the area"))
    if bundle.get("evidence") == "Limited":
        out.append(Fact(signal_id="evidence", severity="medium",
                        label="Limited evidence quality"))
    if 0 < bundle.get("cohort_n", 0) < 20:
        out.append(Fact(signal_id="sample", severity="medium",
                        label="Small historical sample",
                        metric=f"{bundle['cohort_n']} cohort restaurants"))
    return out[:4]


def _fmt_fit(bundle: dict) -> str | None:
    if bundle.get("fit_index") is None:
        return None
    return f"{bundle['fit_index']:.0f} / 100 relative index"


# ------------------------------------------------------------------- risks
def derive_risk_matrix(bundle: dict) -> list[RiskRow]:
    """Categorical risk rows from actual signals — never probabilities."""
    rows: list[RiskRow] = []

    sat = bundle.get("competition_band")
    rows.append(RiskRow(
        category="Competition pressure",
        level=sat if sat in ("Low", "Moderate", "High")
        else "Insufficient evidence",
        evidence="High" if sat else "—",
        why=(f"Comparable restaurant density is {sat.lower()}." if sat
             else "Comparable-density data unavailable.")))

    turn = bundle.get("turnover")
    turn_level = {"Higher observed turnover": "High", "Typical": "Moderate",
                  "Lower observed turnover": "Low"}.get(
        turn, "Insufficient evidence")
    rows.append(RiskRow(
        category="Historical turnover", level=turn_level,
        # Confidence must match the level: an unmeasured row cannot claim
        # medium confidence in a reading that does not exist.
        evidence=("—" if turn_level == "Insufficient evidence"
                  else "High" if bundle.get("cohort_n", 0) >= 20
                  else "Medium"),
        why=(f"Observed area turnover reads: {turn.lower()}." if turn
             and turn != "Limited evidence"
             else "Historical sample too small for a turnover read.")))

    fit = bundle.get("fit_band")
    fit_level = {"Strong": "Low", "Promising": "Moderate",
                 "Mixed": "High"}.get(fit, "Insufficient evidence")
    rows.append(RiskRow(
        category="Concept evidence", level=fit_level,
        # The area's evidence band describes area data generally; it cannot
        # stand as confidence in a concept reading that was never made.
        evidence=("—" if fit_level == "Insufficient evidence"
                  else bundle.get("evidence") or "—"),
        why=(f"Relative concept fit reads {fit.lower()}." if fit
             else ("No cuisine specified — concept-level fit unmeasured."
                   if bundle.get("cuisine") is None
                   else "Local concept sample below the evidence gate."))))

    ped = bundle.get("ped_band")
    rows.append(RiskRow(
        category="Foot-traffic uncertainty",
        # No count site means UNKNOWN, not high risk: absent evidence must
        # never be scored as an adverse finding.
        level=("Insufficient evidence" if ped is None else
               "Low" if ped == "High" else
               "Moderate" if ped == "Moderate" else "High"),
        evidence="Medium" if ped else "—",
        why=(f"Measured DOT counts in the area read {ped.lower()}." if ped
             else "No DOT count site falls inside this area, so foot "
                  "traffic here is unmeasured — not low.")))

    market = (bundle.get("income_context") is not None
              or bundle.get("population") is not None)
    rows.append(RiskRow(
        category="Market evidence",
        level="Low" if market else "Insufficient evidence",
        evidence="High" if market else "—",
        why=("ACS demographic context is available." if market
             else "ACS context is unavailable for this area.")))

    rows.append(RiskRow(
        category="Site-specific uncertainty", level="High", evidence="—",
        why="Area-level analysis only — no specific site was assessed."))
    return rows


# ----------------------------------------------------------------- leaders
_SAT_ORDER = {"Low": 0, "Moderate": 1, "High": 2}
_EV_ORDER = {"High": 2, "Moderate": 1, "Limited": 0}


def comparison_summary(areas: list[dict]) -> tuple[dict, str]:
    """
    (leaders, recommendation) — computed, never model-decided. Ties are
    shown as ties; unmeasured dimensions are named as such.
    """
    leaders: dict = {}

    measured = [a for a in areas if a.get("fit_index") is not None]
    if measured:
        best = max(a["fit_index"] for a in measured)
        leaders["leading_fit"] = [a["name"] for a in measured
                                  if a["fit_index"] == best]
    else:
        leaders["leading_fit"] = []

    with_sat = [a for a in areas if a.get("competition_band") in _SAT_ORDER]
    leaders["lowest_competition"] = []
    leaders["lowest_competition_band"] = None
    if with_sat:
        low = min(_SAT_ORDER[a["competition_band"]] for a in with_sat)
        leaders["lowest_competition"] = [
            a["name"] for a in with_sat
            if _SAT_ORDER[a["competition_band"]] == low]
        # The band travels with the name: "lowest" among three High areas
        # is still High, and reporting the leader alone would imply relief
        # the data does not support.
        leaders["lowest_competition_band"] = ("Low", "Moderate", "High")[low]

    with_ev = [a for a in areas if a.get("evidence") in _EV_ORDER]
    if with_ev:
        top = max(_EV_ORDER[a["evidence"]] for a in with_ev)
        leaders["strongest_evidence"] = [
            a["name"] for a in with_ev if _EV_ORDER[a["evidence"]] == top]
    else:
        leaders["strongest_evidence"] = []

    # A winner is only declared when EVERY selected area was measurable —
    # leading a field the framework could not score for the others is not
    # evidence of leading.
    fit_leaders = leaders["leading_fit"]
    if (len(fit_leaders) == 1 and len(measured) == len(areas)
            and next(a for a in measured
                     if a["name"] == fit_leaders[0]).get("fit_band")
            in ("Strong", "Promising")):
        recommendation = (f"Among the selected areas, {fit_leaders[0]} has "
                          f"the strongest relative fit under the current "
                          f"analytical framework.")
    else:
        recommendation = "No clear winner emerges from the selected areas."
    return leaders, recommendation


# ------------------------------------------------------- deterministic prose
def deterministic_summary(area: AreaReport) -> str:
    """Fallback narrative — one plain sentence per leading signal, built
    entirely from the payload. Used whenever the LLM layer is unavailable."""
    parts = []
    if area.fit_band:
        parts.append(f"relative concept fit reads {area.fit_band.lower()}")
    if area.competition_band:
        parts.append(f"comparable competition is "
                     f"{area.competition_band.lower()}")
    if area.turnover and area.turnover != "Limited evidence":
        parts.append(f"observed turnover is "
                     f"{area.turnover.replace(' observed turnover', '').lower()}")
    if area.ped_band:
        parts.append(f"measured pedestrian activity nearby reads "
                     f"{area.ped_band.lower()}")
    else:
        parts.append("pedestrian evidence is limited")
    body = "; ".join(parts) if parts else "evidence for this area is limited"
    return f"{area.name}: {body}."
