"""Paths and tunable constants. Everything the pipeline knows about the disk."""
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent.parent
RAW = APP_DIR
PROCESSED = APP_DIR / "processed"
PROCESSED.mkdir(exist_ok=True)

# --- Source files -----------------------------------------------------------
HIST_2017 = RAW / "DOHMH_New_York_City_Restaurant_Inspection_Results.csv"
CUR_2026 = RAW / "DOHMH_New_York_City_Restaurant_Inspection_Results_20260824.csv"
SNAP_2021 = RAW / "cleanDb_Aug_31cuisines.csv"
PREPERMIT = RAW / "Pre-Permit_Restaurant_Inspections_20260824.csv"
PLUTO = RAW / "Primary_Land_Use_Tax_Lot_Output_(PLUTO)_20260824.csv"
# 2026-08-25 download; same schema as the 20260824 file it supersedes.
PEDESTRIAN = RAW / "Bi-Annual_Pedestrian_Counts_20260825.csv"

# --- 2024 ACS 5-Year, NYC tracts (generated by scripts/fetch_acs_nyc.py) ----
ACS_CSV = APP_DIR / "data" / "acs_2024_nyc_tracts.csv"
# --- 2020 NTA geography + tract equivalency (user-supplied downloads) -------
NTA_POLYGONS = RAW / "2020_Neighborhood_Tabulation_Areas_(NTAs)_20260825.csv"
TRACT_TO_NTA = RAW / "2020_Census_Tracts_to_2020_NTAs_and_CDTAs_Equivalency_20260825.csv"
# LEGACY / UNUSED: national-level DP05 extract — one geography (the United
# States), no income column. Kept only because it was user-supplied; nothing
# may read it for neighbourhood analysis.
LEGACY_NATIONAL_CENSUS = RAW / "ACSDP1Y2024.DP05-2026-08-24T174616.csv"

# --- Outputs ----------------------------------------------------------------
RESTAURANTS_PQ = PROCESSED / "restaurants.parquet"
LOCATIONS_PQ = PROCESSED / "locations.parquet"
LOTS_PQ = PROCESSED / "lots.parquet"
PEDESTRIAN_PQ = PROCESSED / "pedestrian.parquet"
TRACTS_PQ = PROCESSED / "tracts.parquet"

# --- Observation windows ----------------------------------------------------
# Verified by reading the files, not assumed. The 2017 archive and the 2026
# extract observe two disjoint stretches of time; nothing observes the gap
# between them except the partial 2021 snapshot.
HIST_WINDOW = ("2011-10-07", "2017-08-26")
CUR_WINDOW_START = "2023-01-01"   # where the 2026 rolling window has real density
SNAPSHOT_DATE = "2026-08-24"

# DOHMH writes this when an establishment has never been inspected.
NULL_DATE_SENTINEL = "1900-01-01"

# --- Analysis defaults ------------------------------------------------------
DEFAULT_RADIUS_M = 500
MIN_COMPARABLES = 5      # below this, do not quote a local median
